---
openapi: 3.0.1
info:
  title: ISMS_TEST Api
  version: '1.0'
paths:
  "/path/malformed/by/ISMS_TEST":
    post:
      tags:
      - 1. Web APi
      parameters:
      - name: kbkim
      tags:
      - 2. Alert APi
      parameters:
      - name: kbkim
